[package]
name = "dwbase-pack-runner"
edition.workspace = true
license.workspace = true
version.workspace = true

description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
[dependencies]

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
