[package]
name = "observe_stream"
version = "1.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
tempfile = "3.13.0"

[dependencies.dwbase-core]
path = "../../crates/dwbase-core"

[dependencies.dwbase-engine]
path = "../../crates/dwbase-engine"
features = [
    "tokio",
]

[dependencies.dwbase-security]
path = "../../crates/dwbase-security"

[dependencies.dwbase-storage-sled]
path = "../../crates/dwbase-storage-sled"

[dependencies.dwbase-stream-local]
path = "../../crates/dwbase-stream-local"

[dependencies.dwbase-vector-hnsw]
path = "../../crates/dwbase-vector-hnsw"

[dependencies.dwbase-embedder-dummy]
path = "../../crates/dwbase-embedder-dummy"

[dependencies.tokio]
version = "1.48.0"
features = [
    "macros",
    "rt-multi-thread",
    "time",
]
